CFLAGS = -MT -Wall
LIBPNG = ..\..\libpng
LIBDIR = $(LIBPNG)\Projects\Vstudio\Release Library

all : png2bin.exe

clean :
	del png2bin.exe

png2bin.exe : png2bin.C
    $(CC) $(CFLAGS) -I$(LIBPNG) png2bin.c "$(LIBDIR)\libpng16.lib" "$(LIBDIR)\zlib.lib" -o png2bin.exe
